### ISSUE TITLE
Crashes when clicking edge

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/gamma-viewer#14] opened 2021-03-18 17:35 UTC
1. Using the notebook plugin, I get a message and view it.  
2. Click on Answers Table
3. Use the arrow to open an answer so that the screen looks like:

![image](https://user-images.githubusercontent.com/10744350/111670776-95324d00-87ee-11eb-9273-fb090db50282.png)

Clicking the edge crashes the viewer (it vanishes)

**Comment by cbizon** [comment] 2021-03-18 17:35
Seems to happen no matter what the answer is, but if needed I can provide this exact example.

**Comment by maximusunc** [comment] 2021-03-24 14:05
@cbizon Could you provide this exact example please? All of the messages that I have open the edge explorer modal fine.

**Comment by cbizon** [comment] 2021-03-24 14:21
```
{'message': {'query_graph': {'nodes': {'a': {'id': None,
     'category': 'biolink:ChemicalSubstance',
     'is_set': False},
    'b': {'id': 'NCBIGene:2710', 'category': 'biolink:Gene', 'is_set': False}},
   'edges': {'ab': {'subject': 'a',
     'object': 'b',
     'predicate': None,
     'relation': None}}},
  'knowledge_graph': {'nodes': {'CHEBI:15422': {'category': ['biolink:NamedThing',
      'biolink:MolecularEntity',
      'biolink:Entity',
      'biolink:ChemicalSubstance',
      'biolink:BiologicalEntity'],
     'name': 'ATP',
     'attributes': [{'type': 'NA',
       'value': ["adenosine 5'-(tetrahydrogen triphosphate)",
        'ATP',
        "Adenosine 5'-triphosphate",
        'Adenosine triphosphate',
        "ADENOSINE-5'-TRIPHOSPHATE",
        'H4atp'],
       'name': 'synonyms',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'ATP',
       'name': 'name',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': ['gtpo:1713',
        'DRUGBANK:DB00171',
        'CHEMBL.COMPOUND:CHEMBL14249',
        'MESH:D000255',
        'CHEBI:15422',
        'INCHIKEY:OOCDCJVAHKFZHI-CQSZACIVSA-N',
        'HMDB:HMDB0000538',
        'KEGG:C00002',
        'PUBCHEM.COMPOUND:5957',
        'UNII:8L70Q75FXE'],
       'name': 'equivalent_identifiers',
       'url': None,
       'source': None}]},
    'CHEBI:17754': {'category': ['biolink:NamedThing',
      'biolink:MolecularEntity',
      'biolink:Entity',
      'biolink:ChemicalSubstance',
      'biolink:BiologicalEntity'],
     'name': 'glycerol',
     'attributes': [{'type': 'NA',
       'value': ['glycerol',
        'Glycerol',
        'GLYCEROL',
        'propane-1,2,3-triol',
        '1,2,3-Propanetriol',
        '1,2,3-Trihydroxypropane',
        'Glycerin',
        'glycerine',
        'Glyceritol',
        'glycerolum',
        'glycyl alcohol',
        'Glyzerin',
        'Gro',
        'Oelsuess',
        'Propanetriol',
        'Trihydroxypropane'],
       'name': 'synonyms',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'glycerol',
       'name': 'name',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': ['DRUGBANK:DB09462',
        'MESH:D003451',
        'KEGG:C00116',
        'gtpo:5195',
        'MESH:D005990',
        'HMDB:HMDB0000131',
        'CHEBI:17754',
        'INCHIKEY:FCMSAPXDFYCBGJ-PWJLMRLQSA-N',
        'PUBCHEM.COMPOUND:753',
        'UNII:PDC6A3C0OX',
        'MESH:C043941',
        'CHEMBL.COMPOUND:CHEMBL692'],
       'name': 'equivalent_identifiers',
       'url': None,
       'source': None}]},
    'CHEBI:16761': {'category': ['biolink:NamedThing',
      'biolink:MolecularEntity',
      'biolink:Entity',
      'biolink:ChemicalSubstance',
      'biolink:BiologicalEntity'],
     'name': 'ADP',
     'attributes': [{'type': 'NA',
       'value': ["adenosine 5'-(trihydrogen diphosphate)",
        'ADP',
        "5'-adenylphosphoric acid",
        "Adenosine 5'-diphosphate",
        "ADENOSINE-5'-DIPHOSPHATE",
        'H3adp'],
       'name': 'synonyms',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'ADP',
       'name': 'name',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': ['KEGG:C00008',
        'CHEMBL.COMPOUND:CHEMBL14830',
        'MESH:D000244',
        'HMDB:HMDB0001341',
        'PUBCHEM.COMPOUND:6022',
        'gtpo:1712',
        'CHEBI:16761',
        'INCHIKEY:HMHDTAYXNLPCEI-UHFFFAOYSA-N',
        'MESH:C020332',
        'UNII:61D2G4IYVH'],
       'name': 'equivalent_identifiers',
       'url': None,
       'source': None}]},
    'CHEBI:15978': {'category': ['biolink:NamedThing',
      'biolink:MolecularEntity',
      'biolink:Entity',
      'biolink:ChemicalSubstance',
      'biolink:BiologicalEntity'],
     'name': 'sn-glycerol 3-phosphate',
     'attributes': [{'type': 'NA',
       'value': ['(2R)-2,3-dihydroxypropyl dihydrogen phosphate',
        'sn-glycerol 3-(dihydrogen phosphate)',
        'sn-Glycerol 3-phosphate',
        '(R)-glycerol 1-phosphate',
        'D-(glycerol 1-phosphate)',
        'D-Glycerol 1-phosphate',
        'Glycerol-3-phosphate',
        'Glycerophosphoric acid',
        'L-(glycerol 3-phosphate)',
        'phosphoric acid mono-((R)-2,3-dihydroxy-propyl) ester',
        'Phosphorsaeure-mono-((R)-2,3-dihydroxy-propylester)',
        'SN-GLYCEROL-3-PHOSPHATE',
        'sn-Gro-1-P'],
       'name': 'synonyms',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'sn-glycerol 3-phosphate',
       'name': 'name',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': ['CHEMBL.COMPOUND:CHEMBL1232920',
        'INCHIKEY:YINNFAZGMMIJFN-UHFFFAOYSA-N',
        'UNII:370V52HE4B',
        'HMDB:HMDB0000126',
        'PUBCHEM.COMPOUND:439162',
        'KEGG:C00093',
        'CHEBI:15978',
        'DRUGBANK:DB02515'],
       'name': 'equivalent_identifiers',
       'url': None,
       'source': None}]},
    'NCBIGene:2710': {'category': ['biolink:NamedThing',
      'biolink:MolecularEntity',
      'biolink:BiologicalEntity',
      'biolink:GenomicEntity',
      'biolink:GeneOrGeneProduct',
      'biolink:Gene',
      'biolink:MacromolecularMachine'],
     'name': 'GK',
     'attributes': [{'type': 'NA',
       'value': [],
       'name': 'synonyms',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'GK',
       'name': 'name',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': ['NCBIGene:2710',
        'HGNC:4289',
        'UniProtKB:P32189',
        'NCBIGene:2710',
        'ENSEMBL:ENSG00000198814'],
       'name': 'equivalent_identifiers',
       'url': None,
       'source': None}]}},
   'edges': {'774fe02786513ea94ec35a344755c528': {'subject': 'NCBIGene:2710',
     'object': 'CHEBI:17754',
     'predicate': 'biolink:increases_degradation_of',
     'relation': None,
     'attributes': [{'type': 'NA',
       'value': 'increases degradation of',
       'name': 'relation_label',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 1604318245.068261,
       'name': 'ctime',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'kegg.chemical_get_enzyme',
       'name': 'provided_by',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'CHEBI:17754',
       'name': 'target_id',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'NCBIGene:2710',
       'name': 'source_id',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'kegg',
       'name': 'source_database',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'CTD:increases_degradation_of',
       'name': 'relation',
       'url': None,
       'source': None},
      {'type': 'EDAM:data_0971',
       'value': [],
       'name': 'publications',
       'url': None,
       'source': None}]},
    'd7d01150b89f887cc3a863a35c873bb5': {'subject': 'NCBIGene:2710',
     'object': 'CHEBI:15978',
     'predicate': 'biolink:increases_synthesis_of',
     'relation': None,
     'attributes': [{'type': 'NA',
       'value': 'increases synthesis of',
       'name': 'relation_label',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 1604317276.2124817,
       'name': 'ctime',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'kegg.chemical_get_enzyme',
       'name': 'provided_by',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'CHEBI:15978',
       'name': 'target_id',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'NCBIGene:2710',
       'name': 'source_id',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'kegg',
       'name': 'source_database',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'CTD:increases_synthesis_of',
       'name': 'relation',
       'url': None,
       'source': None},
      {'type': 'EDAM:data_0971',
       'value': [],
       'name': 'publications',
       'url': None,
       'source': None}]},
    '236eaaf7d5787a08b6972b58b11532bb': {'subject': 'NCBIGene:2710',
     'object': 'CHEBI:15422',
     'predicate': 'biolink:increases_degradation_of',
     'relation': None,
     'attributes': [{'type': 'NA',
       'value': 'increases degradation of',
       'name': 'relation_label',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 1604291125.6539216,
       'name': 'ctime',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'kegg.chemical_get_enzyme',
       'name': 'provided_by',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'CHEBI:15422',
       'name': 'target_id',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'NCBIGene:2710',
       'name': 'source_id',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'kegg',
       'name': 'source_database',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'CTD:increases_degradation_of',
       'name': 'relation',
       'url': None,
       'source': None},
      {'type': 'EDAM:data_0971',
       'value': [],
       'name': 'publications',
       'url': None,
       'source': None}]},
    '0b24bc573b87d26962ef3ca2735a0aab': {'subject': 'NCBIGene:2710',
     'object': 'CHEBI:16761',
     'predicate': 'biolink:increases_synthesis_of',
     'relation': None,
     'attributes': [{'type': 'NA',
       'value': 'increases synthesis of',
       'name': 'relation_label',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 1604300467.0079234,
       'name': 'ctime',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'kegg.chemical_get_enzyme',
       'name': 'provided_by',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'CHEBI:16761',
       'name': 'target_id',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'NCBIGene:2710',
       'name': 'source_id',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'kegg',
       'name': 'source_database',
       'url': None,
       'source': None},
      {'type': 'NA',
       'value': 'CTD:increases_synthesis_of',
       'name': 'relation',
       'url': None,
       'source': None},
      {'type': 'EDAM:data_0971',
       'value': [],
       'name': 'publications',
       'url': None,
       'source': None}]}}},
  'results': [{'node_bindings': {'a': [{'id': 'CHEBI:17754'}],
     'b': [{'id': 'NCBIGene:2710'}]},
    'edge_bindings': {'ab': [{'id': '774fe02786513ea94ec35a344755c528'}]}},
   {'node_bindings': {'a': [{'id': 'CHEBI:15978'}],
     'b': [{'id': 'NCBIGene:2710'}]},
    'edge_bindings': {'ab': [{'id': 'd7d01150b89f887cc3a863a35c873bb5'}]}},
   {'node_bindings': {'a': [{'id': 'CHEBI:16761'}],
     'b': [{'id': 'NCBIGene:2710'}]},
    'edge_bindings': {'ab': [{'id': '0b24bc573b87d26962ef3ca2735a0aab'}]}},
   {'node_bindings': {'a': [{'id': 'CHEBI:15422'}],
     'b': [{'id': 'NCBIGene:2710'}]},
    'edge_bindings': {'ab': [{'id': '236eaaf7d5787a08b6972b58b11532bb'}]}}]},
 'knowledge_graph': {'nodes': [], 'edges': []},
 'results': []}
```

**Comment by maximusunc** [comment] 2021-03-24 15:10
Issue fixed in v.0.2.1. The issue was caused by the UI not handling null values in edge properties when displaying the edge explorer modal.

A few notes on the example message you posted:
- There are extra top-level knowledge_graph and results in this message. The UI doesn't care about them, but it's unusual that they're in there.
- 'None' and 'False' properties aren't valid JSON. They should be 'null' and 'false' respectively. I'm assuming you fixed them locally or else the notebook would have thrown an error when trying to read the file.

**Closed by maximusunc** 2021-03-24 15:10 UTC
